### ISSUE TITLE
[hasChanges]

### ISSUE THREAD

**Issue by BayramInanc** [VergeGroup/swift-Verge#316]
![image](https://user-images.githubusercontent.com/12694849/208282863-f340b659-1ec1-4c0c-909b-06ef24669915.png)

Even if empty function does nothin, hashChanges is true. Why is that? I made the derived pipeline type memoized, still it has no effects. I also set counter the same value, hasChanges again true.

**Comment by muukii** [comment]
May I see your code?

**Comment by BayramInanc** [comment]
This class is inside verge library's test package. I played with it and wonder why that happened?

**Comment by BayramInanc** [comment]
DerivedTests.swift class

**Comment by muukii** [comment]
Oh I see you're wondering why empty commit won't make changes.
Verge commit checks if there are any changes or not.
It won't nothing if there is no changes.

**Comment by BayramInanc** [comment]
But ı set counter value again lets say previous is 2, I set 2 again . Still haschanges true. Should not it be haschanges false? In this case prev and current became 2

**Comment by muukii** [comment]
ah I get it.
commit won't make a new state if there is no changes inside commit.

so you can attention to the version property. this means version of the state.
it would be incremented after commit applied.

so means using the same state after empty commit

**Comment by BayramInanc** [comment]
Then it means even if I set the same value, haschanges will not change. In this case for example if it was true then it wll be true. However, version will change right?

**Comment by muukii** [comment]
if you set true and current is true. you will get a new state as new version.

**Comment by muukii** [comment]
> commit won't make a new state if there is no changes inside commit.

meaning, you won't get new callback in `Store.sinkState` because Store won't make new state.
it differs between commit as empty and commit with same value.

**Comment by BayramInanc** [comment]
thank you. I have been exploring Verge for 3 days. I get so impressed.

**Comment by muukii** [comment]
@BayramInanc thanks for asking. anytime I will help you.
