### ISSUE TITLE
[On Verge-Orm]

### ISSUE THREAD

**Issue by BayramInanc** [VergeGroup/swift-Verge#319]
I did not understan why we need Verge Orm? Which case should we add to our project? Can you give some use cases for understanding? I think, in Verge we really do not normalizaton stuff like in Mobx. Am ı wrong?

**Comment by muukii** [comment]
@BayramInanc 
It's not necessary if you don't use such a complex state, as like so many records in there.
Verge uses a struct that is compatible with Equatable first. Normalization is not there.
VergeORM package brings normalization techniques there.
