### ISSUE TITLE
Initializer requires that EventEmitter conform to 'DispatcherType'

### ISSUE THREAD

**Issue by darnfish** [VergeGroup/swift-Verge#412]
Hey there,

I'm trying to use Verge and VergeORM in my application. Right now I have a very small model with a couple entries and I'm trying to list all the entries using SwiftUI:
```swift
VStack {
    StoreReader(Pickup.shared.store) { state in
        VStack {
            ForEach(state.database.entities.home.allEntities()) { home in
                Text("\(home.rawID)")
            }
        }
    }
}
```

But on the `StoreReader` line, I get the following error:
`Initializer 'init(debug:_:content:)' requires that 'EventEmitter<_StoreEvent<State, Never>>' conform to 'DispatcherType'`

This seems to only happen if I add the ForEach block. Let me know if there's another way I should be doing this :~)

**Comment by muukii** [comment]
I guess that ForEach requires the entity needs to conform to Identifiable?

**Comment by darnfish** [comment]
Even when supplying an id field, it still errors :~(

<img width="1143" alt="Screen-Shot-2023-08-30-15-12-14 39" src="https://github.com/VergeGroup/swift-Verge/assets/8293444/a59c07bb-d834-4a9c-b7df-0fb0e53ebf63">

**Comment by muukii** [comment]
ah probably, allEntities() returns AnyCollection. seems it does not fit with ForEach.init

**Comment by darnfish** [comment]
Do you know what I should do to work around this issue?

**Comment by muukii** [comment]
currently, allEntities() is not efficient but you could cast into Array. that may work

**Comment by darnfish** [comment]
I'll try it, but I've since moved onto a different library. Hoping I can revisit this one in a couple years :~)
