### ISSUE TITLE
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

### ISSUE THREAD

**Issue by baronha** [VergeGroup/swift-Verge#461]
I am using SwiftUI combine State effect by `StoreReader {}`. 
But there is an error warning and the UI freezes, I don't know what to do?

<img width="1126" alt="Screenshot 2024-02-19 at 01 33 16" src="https://github.com/VergeGroup/swift-Verge/assets/23580920/f9954397-1e43-4f67-8b7d-e1177efa166d">

xCode: Version 15.0 (15A240d)
IPhone RealDevice: iPhone 11 - iOS 16.5.1

**Comment by muukii** [comment]
what type of _publisher is it?

**Comment by baronha** [comment]
> what type of _publisher is it?

It gives an error here and I don't know the cause. Sorry.
https://github.com/VergeGroup/swift-Verge/blob/2e428233a1036ce851e094c639b56c6583d09b0d/Sources/Verge/SwiftUI/StoreReader.swift#L255

**Comment by muukii** [comment]
oh, okay! it's inside Verge.

**Comment by muukii** [comment]
It seems like it should dispatch in a hop (like Task { @MainActor in ... }) to escape view updating operation, and I'm not sure that is suitable operation any time.
I'd like to know how the call stack is. Could you reproduce it easily in your environment?

**Comment by baronha** [comment]
Here's how I use it in the project:

I have a `EditorModel Class`:

```swift
class EditorModel: ObservableObject {
    private var subscriptions = Set<AnyCancellable>()

    @Published var toolbar: ToolItem = .none
    @Published var stack: EditingStack
    
}
```
EditingStack is class of [Brightroom](https://github.com/FluidGroup/Brightroom)

https://github.com/FluidGroup/Brightroom/blob/fec3654216b5f551281a05ccc153dedb7696b246/Sources/BrightroomEngine/Core/EditingStack.swift#L72

And SwiftUI View using StoreReader:

``` swift

import SwiftUI
import Verge

struct Filter: View {
    @State private var tagActive: Int8 = 0
    @State private var loading: Bool = false
    @EnvironmentObject private var editorModel: EditorModel
    private var subscriptions = Set<AnyCancellable>()

    @Environment(\.isPreview) var isPreview

    var body: some View {
        if !isPreview {
            FilterTag(tagActive: $tagActive)
        }

        StoreReader(editorModel.stack.store) { state in
            VStack(spacing: 0) {
                if !state.isLoading {
                    FilterRow(tagActive: $tagActive)
                } else {
                    FilterRowSkeleton()
                }
            }
        }
    }
}

```
I don't know if my usage is correct.

**Comment by muukii** [comment]
I made a next version.
try this on
https://github.com/VergeGroup/swift-Verge/releases/tag/12.1.0

**Comment by baronha** [comment]
When I updated Verge to 12.1.0 then `Brightroom` had a problem with `primitiveState`. I changed it to `state` and everything was resolved. Is there a difference between `primitiveState` and state?

<img width="664" alt="Screenshot 2024-02-23 at 00 21 48" src="https://github.com/VergeGroup/swift-Verge/assets/23580920/57d1fd84-22d8-4e9a-95d9-12bc6e173c52">

**Comment by muukii** [comment]
@baronha 
there is no difference. no worries
